version: '3.8'

services:
  web:
    build:
      context: .                   # Specifies the build context (the root of your project)
      dockerfile: Dockerfile.dev   # Uses the development Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"                # Maps port 8000 on the host to port 8000 in the container
    volumes:
      - .:/app                     # Mounts the current directory to /app in the container
    environment:
      - DJANGO_SETTINGS_MODULE=QuantumCo.settings  # Points to your development settings module
      - DEVELOPMENT_MODE=True

#docker-compose -f docker-compose.dev.yml up --build
#docker-compose -f docker-compose.dev.yml up

#Executes the migration inside the Docker container for your Django app
#docker-compose -f docker-compose.dev.yml exec web python manage.py migrate
